//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Library.Commands.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Library.Commands.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ArgSeperator는 SwitchDelimiter과 다른 문자여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ArgSeperatorAndSwitchDelimiterCannotBeTheSame {
            get {
                return ResourceManager.GetString("ArgSeperatorAndSwitchDelimiterCannotBeTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ArgSeperator는 문장부호여야만 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ArgSeperatorMustBeAPunctuation {
            get {
                return ResourceManager.GetString("ArgSeperatorMustBeAPunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 가능한 명령들과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AvaliableCommands {
            get {
                return ResourceManager.GetString("AvaliableCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입컨버터에서 문자열에 의한 변환이 지원되질 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotConvertFromString {
            get {
                return ResourceManager.GetString("CannotConvertFromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설명과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   잘못된 인수 형식입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidArgumentType {
            get {
                return ResourceManager.GetString("InvalidArgumentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스위치의 이름은 문자 또는 숫자여야만 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSwitchName {
            get {
                return ResourceManager.GetString("InvalidSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   유효하지 않은 스위치가 포함되어 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidSwitchWasIncluded {
            get {
                return ResourceManager.GetString("InvalidSwitchWasIncluded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   the MIT License http://www.opensource.org/licenses/mit-license.php.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   타입이 정적 클래스이여야만 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MustBeStaticClass {
            get {
                return ResourceManager.GetString("MustBeStaticClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MutuallyExclusive가 같은 스위치는 Required 속성값이 모두 true거나 false여야 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MutuallyExclusiveException {
            get {
                return ResourceManager.GetString("MutuallyExclusiveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   같은 값의 상호배타적 스위치가 이미 설정되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MutuallyExclusiveSwitchIsAlreadySet {
            get {
                return ResourceManager.GetString("MutuallyExclusiveSwitchIsAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   전달인자가 한개도 포함되어 있지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoArguments {
            get {
                return ResourceManager.GetString("NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   해당 스위치를 찾을 수가 없거나 잘못된 인자 형식입니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotFoundMatchedSwitch {
            get {
                return ResourceManager.GetString("NotFoundMatchedSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택 인수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필수 인수과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   요약과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SwitchDelimiter 는 문장부호여야만 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchDelimiterMustBePunctuation {
            get {
                return ResourceManager.GetString("SwitchDelimiterMustBePunctuation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   필요한 스위치가 빠져있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchIsMissing {
            get {
                return ResourceManager.GetString("SwitchIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   스위치가 이미 등록되어 있습니다. 중복여부를 확인하세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SwitchWasAlreadyRegistered {
            get {
                return ResourceManager.GetString("SwitchWasAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   사용 방법과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Usage {
            get {
                return ResourceManager.GetString("Usage", resourceCulture);
            }
        }
    }
}
